env:
  browser: false
  es6: true
  jest: true
extends: airbnb-base
parser: babel-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  babelOptions:
    configFile: "/app/babel.config.js"
rules:
  import/prefer-default-export: 0
  max-len:
    - 2
    - 180
