env:
  browser: false
  es6: true
  jest: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  import/prefer-default-export: 0
  max-len:
    - 2
    - 120
